import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { TanstackProvider } from "@/components/providers/tanstack-provider";
import ThemeProvider from "@/components/providers/theme-provider";
import NotificationProvider from "@/components/providers/notifications-provider";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${robotoSans.className}`}>
        <TanstackProvider>
          <ThemeProvider>
            <NotificationProvider>
              <main className='p-6'>{children}</main>
            </NotificationProvider>
          </ThemeProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}

